/**
 * @overview generated by ghoti-cli
 * @fileoverview routes configs
 */

import * as React from 'react';
import * as Pages from '../page/import';

import Root from './root';

export default (props) => {
    const routes = [
        {
            component: Root,
            routes: [
                {
                    component: Pages.index,
                    exact: true,
                    path: '/',
                }
            ],
        },
    ];
    return routes;
};
