/**
* @overview generated by ghoti-cli
* @fileoverview components import file
* You should not edit this file by hand
*/

import ComponentGhotiFlier from './flier.component';
export {
    ComponentGhotiFlier as flier,
};
