/**
* @overview generated by ghoti-cli
* @fileoverview page import file
* You should not edit this file by hand
*/

import PageGhotiIndex from './index.page';
export {
    PageGhotiIndex as index,
};
