/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiIndex
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

export interface IProps {

}

export interface IState {

}

class PageGhotiIndex extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div>
            <span>Hello, PageGhotiIndex!</span>
        </div>);
    }
}

export default PageGhotiIndex;
